version: '3.8'

services:
  neo4j:
    image: neo4j:5.23-community
    container_name: neo4j-test
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-a", "bolt://localhost:7687", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  neo4j-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neo4j-exporter
    ports:
      - "5000:5000"  # Exporter metrics endpoint
    environment:
      - NEO4J_SERVICE=neo4j
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped

volumes:
  neo4j-data:
  neo4j-logs:
