name: Build and Push Docker Images

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - 'neo4j_exporter/**'
      - '.github/workflows/docker-publish.yml'

env:
  DOCKERHUB_REPO_TERRAFORM: ricklin/terraform
  DOCKERHUB_REPO_NEO4J_EXPORTER: ricklin/neo4j_exporter
  TERRAFORM_VERSION: 1.13.1

jobs:
  echo_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  build-and-push-terraform:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'terraform/') || contains(github.event.head_commit.added, 'terraform/')

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker Hub username
        run: echo "DOCKER_USER is ${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Push git tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.MY_GITHUB_TOKEN }}"
          tag: "${{ env.TERRAFORM_VERSION }}-${{ steps.vars.outputs.sha_short }}"

      - name: Build and push Terraform image
        uses: docker/build-push-action@v5
        with:
          context: ./terraform
          file: ./terraform/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO_TERRAFORM }}:latest
            ${{ env.DOCKERHUB_REPO_TERRAFORM }}:${{ env.TERRAFORM_VERSION }}-${{ steps.vars.outputs.sha_short }}

  build-and-push-neo4j-exporter:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'neo4j_exporter/') || contains(github.event.head_commit.added, 'neo4j_exporter/')

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker Hub username
        run: echo "DOCKER_USER is ${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Neo4j Exporter image
        uses: docker/build-push-action@v5
        with:
          context: ./neo4j_exporter
          file: ./neo4j_exporter/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO_NEO4J_EXPORTER }}:latest
            ${{ env.DOCKERHUB_REPO_NEO4J_EXPORTER }}:${{ steps.vars.outputs.sha_short }}
