name: Build and Push Docker Images

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - '.github/workflows/docker-publish.yml'

env:
  DOCKERHUB_REPO_TERRAFORM: ricklin/terraform
  TERRAFORM_VERSION: 1.12.2

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker Hub username
        run: echo "DOCKER_USER is ${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create and push git tag
        run: |
          TAG_NAME="${{ env.TERRAFORM_VERSION }}-${{ steps.vars.outputs.sha_short }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "$TAG_NAME" -m "Terraform ${{ env.TERRAFORM_VERSION }} build from commit ${{ steps.vars.outputs.sha_short }}"
          git push origin "$TAG_NAME"

      - name: Build and push Terraform image
        uses: docker/build-push-action@v5
        with:
          context: ./terraform
          file: ./terraform/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO_TERRAFORM }}:latest
            ${{ env.DOCKERHUB_REPO_TERRAFORM }}:${{ env.TERRAFORM_VERSION }}-${{ steps.vars.outputs.sha_short }}
